### ISSUE TITLE
Can not put Fotos > 2MB to Picture Library

### ISSUE THREAD

**Issue by HtHNightwolf** [lansuite/lansuite#1074]
## Expected Behavior
I can upload nowaday's regular sized photos.

## Current Behavior
I can not upload nowaday's regular sized photos. Srsly, who still wants to downsize to 2MB? :D

## Possible Solution
Alow uploads of regular sized photos (Max MB maybe 12 or 20).

## Steps to Reproduce (for bugs)
1. Go to picture library
2. Try to upload a pic beyond 2MB
![grafik](https://github.com/lansuite/lansuite/assets/17451169/35cb4b2f-b86d-417a-b1c5-66ab02c648e8)

**Comment by M4LuZ** [comment]
Hi @HtHNightwolf ,

the max upload size is determined based on the server config (php.ini setting `upload_max_filesize`), so it is your webserver config that may need a change ;)
Please have a look and report value back (e.g. check phpinfo), I'll leave ticket open to ensure that it is not actually a bug

(also because you can upload lager files does not mean that you should. 
2MB are actually fine with some compression)

**Comment by M4LuZ** [comment]
Kind reminder, so that we can either investigate or close this

**Comment by M4LuZ** [comment]
Closing as no feedback was provided and this appears to be related to a server misconfiguration, not an issue with Lansuite
