### ISSUE TITLE
Live und DEV system

### ISSUE THREAD

**Issue by Pimmal** [lansuite/lansuite#1139]
I cloned lansuite into a dev subfolder, copied the DB and changed the URL.

Now I have the issue when I change user permissions in the DEV system, the user also gets changed in the live system. But both systems using different DB´s. Why?

Dev system
![image](https://github.com/lansuite/lansuite/assets/20731374/cae69ce0-ada0-4e8f-9760-0292386b830e)

Live system
![image](https://github.com/lansuite/lansuite/assets/20731374/a1e5bae5-8f38-4875-ae5d-d6162fbb84ac)

**Comment by M4LuZ** [comment]
Hi @Pimmal ,

I'm terribly sorry, this is caused by an oversight in the cache implementation.
Both instances share the same cache instance and thus any change in the config file is taken over (with a delay) by both instances.
This does not appear as issue as long as environments do not run within the same server context, thus this was sadly not found earlier.
I hope there was no change to critical data before this was found?

There is an easy workaround, but it requires manual modification of index.php (line 27):
Modify "lansuite" to a value unique for the installation in both rows, that ensures that a different cache pool is used.

```
 // Initialize Cache. Go for APCu first, filebased otherwise. DB adaptor to be used when we implement PDO.
if (extension_loaded('apcu')) {
    $cache = new Symfony\Component\Cache\Adapter\ApcuAdapter('lansuite', 600);
} else {
    $cache = new Symfony\Component\Cache\Adapter\FilesystemAdapter('lansuite', 600);
}
```

The fix itself is a bit more tricky, I'll ponder this a bit and summarize options later.

**Comment by andygrunwald** [comment]
@M4LuZ What would be useful: To generate a random string that is written back to the base config and used as a namespace in like `lansuite-<random>` as a first argument, see https://symfony.com/doc/current/components/cache/adapters/apcu_adapter.html

This would solve it with an easy implementation

**Comment by M4LuZ** [comment]
@andygrunwald That does not work as cache is initialized before config file is read (in order to cache the config file contents)
What we would need is a unique identifier available at the start of `index.php`
Thus more pondering needed.

As said I'll write up options later, in quick and dirty I see the following:
* Use path from webroot upwards as UID
* define constant somewhere during composer init / first setup
* use Apache/Nginx Environment variables
* Remove config cache and trust/ensure that it is kept in WS cache / opcache

**Comment by M4LuZ** [comment]
| Option | Description | Advantages | Disadvantages |
|-------|---------|---------|----------|
Heres the quick write-up:

| Use LS-UUID | Generate and store an (U)UID for cache pool | * No external depencies </br> * moves with the code  | * No easy/nice way to do this. Must be in a file, but it cannot be the config file (as that is read later). So a separate file for the UID, which put the file-caching ad absurdum, as that was to avoid a file read in the first place </br> * additional complexity to ensure that an UUID is generated on first access |
|Use environment variable | Define an environment variable in the site-specific config of Apache / Ngingx and use that| * Available before first line of code | * Adds an implict dependency </br>* Requires user to (be able to) modify WS config </br>* Does not move with the code. If the folder is renamed, the config does no longer apply |
| Use webroot path | Read filesystem location and use part of webroot upwards as key | * no manual work required </br> * no initialisation needed | * is affected by folder renaming </br> * has conflict if multiple web roots are used </br> * may lead to unexpected behavior if two instances are swapped by renaming (e.g. test & prod) | 
| remove config caching, add UID entry | Remove caching of config file, write a UID entry and use that | * No external dependencies </br> * simple to implement </br> * prevents use of stale config on changes of config file | * increases FS access, if file is not cached by Webserver / FS |


Given this I think the removal of config file caching is the best option.
That also solves the issue that config file changes are not immediately applied, as old content is in cache.
