### ISSUE TITLE
Cannot install Lansuite

### ISSUE THREAD

**Issue by lukrei** [lansuite/lansuite#1191]
I cannot install Lansuite on debian 12 and MariaDB Version 10.11.6 and php 8.1.29 fpm.
During the installation the web installer asks me to create an admin account but admin account cannot be created.
During Step 6 setup wants me to create a admin user however this is not possible:
index.php?mod=install&action=wizard&step=6
In the apache error.log i get this message after i clicked on the Add button in step 6:
[proxy_fcgi:error] [pid 13776] [client 192.0.2.254:44170] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "design" in /var/www/lansuite/index.php on line 437', referer:

I also tried to change theme to OSx or something else but no difference.

Can someone please help me to install this version of lansuite?

**Comment by M4LuZ** [comment]
Hi @lukrei ,

this is a known regression that was already raised as #1136 
Both that and the warning will be fixed with merge of PR #1193 
Our focus is currently on refactoring the codebase and keeping current installations running, but happy to get yet another user.

But: 
I would suggest that you give your other ticket #1192 an overhaul if you want any feedback or help on that
