### ISSUE TITLE
Manually changing translations not working

### ISSUE THREAD

**Issue by TheDeadCPU** [lansuite/lansuite#345]
When changing translations in a module via the GUI in module-configuration the changes do not propegate.
Changing the translation manually in the translation.xml file for the module also does not make a difference.

## Expected Behavior

Changing a line, and hitting "editieren" should propegate the change in the line to system.

## Current Behavior

Changing a line, and hitting "editerien" does no change, the line is back to what it was before.

## Steps to Reproduce (for bugs)

1. Enter translation tab on a module config page
2. Change a line in the translations
3. Click editieren
4. Go back to translation tab - Line will be back to standard.

## Your Environment

* Version used: Latest
* Operating System and version: Ubuntu Server 18.04 
* Docker Version: 18.06.1-CE
* Docker Compose Version: 1.22.0

**Comment by TheDeadCPU** [comment]
I'm unsure how to get logs for this, I'm guessing this is handled in a database?
I've checked the logs in the GUI and also looking at my terminal but see no traces of this action being done.

Could I possibly connect to the database and manually change the translations there?

**Comment by M4LuZ** [comment]
Confimed: translations added by the translation tab are not stored and revert to their default value

XML changes are not directly taken over as translations are read and stored in the DN once on module initialisation and are only read from there afterwards.

You can trigger a reprocessing of the XML files through the translation functionality in the Admin-Page (`"Admin-Seite"->"Übersetzungen"->"mod_translation.xml auslesen und in DB schreiben (alle Module)"`)

Give that a try, hopefully it works for you as expected.
It should be possible to edit the translations also in the DB, but I would consider that a last resort.

We would be very happy if you could provide us with your translations so that we can re-integrate them once you are done with them

**Comment by M4LuZ** [comment]
Found the issue and created a pull request for the fix.
Thanks for the bug report, most of our users are german, so translations aren't trialed as much as we would like
