### ISSUE TITLE
License switch from GPL to MIT / BSD / Apache 2?

### ISSUE THREAD

**Issue by andygrunwald** [lansuite/lansuite#7]
LanSuite is currently licensed according GPL v2.
According to many projects and open source contributors. One reason is that every module has to apply the GPL license as well and it must be open source.
Some contributors might not like this.

## Suggestion

My suggestion would be to change the license to a more open and more well accepted license like [MIT](https://choosealicense.com/licenses/mit/), BSD or [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/).

Those licenses are more open to the things you can do with the code, e.g. use it in a commercial way and not need to provide the source to everyone or have the freedom to choose a different license.

More information are available at https://choosealicense.com/

## But how do we switch a license?

Good question.
[Doctrine switches from LGPL to MIT](https://beberlei.de/2012/05/26/doctrine_goes_mit.html) a few years back.
For this purpose they had written the [doctrine/license-manager](https://packagist.org/packages/doctrine/license-manager) application for it.

As far as i know you have to get the agreement from every contributor.
If the contributor don't agree, you have to rewrite or remove those code parts.

**Comment by jannaahs** [comment]
If we change the license, I would prefer [Apache 2.0](https://choosealicense.com/licenses/apache-2.0/).

**Comment by andygrunwald** [comment]
100% fine for me as well.
@M4LuZ @JochenJung Any opinion about this?

**Comment by M4LuZ** [comment]
I would say we cross that bridge when we come to it. 
We have yet to find a case where the GPLv3 would influence our development, so why should we now invest the time?

What we could do very easily is to extend the readme to basically say:
`LS currently licensed under GPLv3, but please contact us if you require access under a different license model.`
And if somebody ever contacts us, we re-open this issue ;)

**Comment by JochenJung** [comment]
Im not very familiar with licensing. I would prefer a liberal license as well, if its possible to change.

**Comment by M4LuZ** [comment]
It is possible but would AFAIK require to get the agreement of all contributors that their code can be used under a different licence. 
If if cannot be received, then their code pieces have to be removed / rewritten.
And I would very much like to avoid that unless we have a very good reason for it

**Comment by andygrunwald** [comment]
I agree you @M4LuZ.
But over time we (hopefully) more contributor. This would mean that it is getting harder over time to reach all people.

**Comment by lxp** [comment]
I don't think GPL is a big problem here. A licence like AGPL would be more problematic.
When you write a LanSuite module right now, the module has to be licensed GPL, because LanSuite is licensed GPL.
However, that doesn't mean that you have to provide source code to the general public.
If you only use your module on your pages and don't publish a binary/obfuscated version of your module, you don't have to provide source code to anyone.
GPL only forbids you to distribute binary versions of your module without source code.
However, I think this is not a that common use case in the PHP world.

This are just my 2 cents. If the general consent is to switch licence, I won't be blocking that in any way and will support it.

**Comment by andygrunwald** [comment]
We will keep it as is right now and change it when needed.
If someone has concerns or more feedback, feel free to add a comment here and we will reopen the issue.
