### ISSUE TITLE
Offer full package builds including all dependencies

### ISSUE THREAD

**Issue by lxp** [lansuite/lansuite#89]
This is a continuation of the discussion started here: https://github.com/lansuite/lansuite/pull/81#issuecomment-315633209

### What are you expecting the "full package" to contain?

> By full package I mean a ready-to-go installation source as previously provided.
Meaning the full source code with all dependencies, so that any user with just basic webhosting can get it up and running without resorting to a second machine with shell access to prepare the installation.

### Open questions

- Where should we build them?
- Where should we publish them?
- How often should we build and publish them?
  For each commit on master? Only for releases?

### Suggestions

- Build on Travis CI, as we already have Travis CI running for some checks
- Publish on GitHub
- For each commit in master and on releases

I don't have experience with real builds on Travis (only with tests) and I also don't have experience with publishing releases on GitHub.
So are my suggestions even sane? Can we differentiate between "dev" and "release" builds on GitHub without confusing our users?

**Comment by andygrunwald** [comment]
> Where should we build them?

Locally or on a central CI System.
Locally (due to a shell script) would be an easy start.
A central CI system would be a good choice, but requires maintenance and hosting.

> Where should we publish them?

Github offers downloadable releases incl. zip / tar packages. See https://github.com/gohugoio/hugo/releases as an example.

I prefer Github releases, because they are public accessible, easy to create and maintain.

I don't know it a "dev" release is necessary. This can be (IMO) the master branch itself.

**Comment by M4LuZ** [comment]
I would say we should go for a central system.
As soon as we start with unit tests, we need to pull all source files to fulfil code inclusions.
Won't be much additional work to tar&gzip that working folder and offer it as nightly build or "real" release.
(But that could also be modeled as shell script that is then just executed by the build system, which would have the benefits of both)

+1 regarding GitHub releases, 
It does have some charm to keep everything we need within GitHub and Travis.
